### ISSUE TITLE
full exe analysis does not work properly on x64 bit dbg

### ISSUE THREAD

**Issue by winkerbie** [ThunderCls/xAnalyzer#12]
Selecting to analyse specific function works well - everything is populated properly

However when selecting to "Analyze Executable" - it completes analysis and then shows a brief glimpse of the commented code, then just deletes it?? No function defining black bars either...

Only tested on x64 version not sure about the x32 one

**Comment by ThunderCls** [comment]
Is this happening with a particular executable or with each one you try?. Could you provide the executable and maybe some brief steps to reproduce this behavior?
