### ISSUE TITLE
Bug while "Analyze Selection"

### ISSUE THREAD

**Issue by gmastergreatee** [ThunderCls/xAnalyzer#23]
![xanalyzer bug](https://user-images.githubusercontent.com/17880848/29498137-8cac2c72-8613-11e7-93aa-2c814723ba16.gif)

**Comment by ThunderCls** [comment]
That's not a bug, its a feature actually. To disable this behaviour you need to tick every checkbox under the "Clear Previous Data" menu

**Comment by gmastergreatee** [comment]
My bad! Thanks for the info :+1:
