### ISSUE TITLE
Can't work on x64dbg

### ISSUE THREAD

**Issue by haroldrandom** [ThunderCls/xAnalyzer#25]
My x64dbg version is 2017-12-26-13-39, and the xAnalyzer is 2.4.3.

I get nothing output on the Disassambler Window after finishing the installation and then analyzing an exe file.

What's the problem? Do I miss some necessary step?

**Comment by ThunderCls** [comment]
It works without issues for me on both x86 and x64 versions. Im using the 2017-12-26 snapshot of x64dbg just like you and have no problems whatsoever. Be sure to check the log messages on the log tab of x64dbg and look for any message xAnalyzer related, if you cant find anything there then you are gonna have to give more details or perhaps upload the executable your trying to analyze.

**Comment by haroldrandom** [comment]
There it is.

After right click analyze selection or function or executable, I got the log output below.

```
[xAnalyzer]: Doing analysis, please wait... 
Starting xref analysis...
49658 xrefs found in 219ms!
Starting xref analysis...
49658 xrefs found in 218ms!
[xAnalyzer]: Doing extended analysis... 
[xAnalyzer]: Extended analysis completed in 0.002000 secs 
[xAnalyzer]: Analysis completed in 1.411000 secs 
[xAnalyzer]: Execution Summary 
------------------------------- 
 - Defined Functions Detected: 0 
 - Undefined Functions Detected: 0 
 - VB DllFunctionCalls Stubs Detected: 0 
 - Total Functions Detected: 0 
 - Total Loops Detected: 0 
 - Total Comments Set: 0 
 - Total Labels Set: 0 
------------------------------- 
```

My xanalyzer.ini
```
[settings]
analysis_extended=false
analysis_undefunctions=false
analysis_auto=false
clear_usercomments=false
clear_userlabels=false
clear_autocomments=false
clear_autolabels=false
```

The executable I am trying to analyzing is then game, AssauleCube. The name is **ac_client.exe**, actually.
It can be download from https://assault.cubers.net/ .

**Comment by ThunderCls** [comment]
Check at the begining of the log for the lines
![image](https://user-images.githubusercontent.com/13303069/34420524-0fa3384e-ebd8-11e7-857c-f5770a203c3a.png)

Also try with the following config
![image](https://user-images.githubusercontent.com/13303069/34420493-e0c5a32c-ebd7-11e7-851e-2f8c2e8b127e.png)

**Comment by haroldrandom** [comment]
Got it. It works now. Thank you for you time.
