### ISSUE TITLE
Cannot remove old non-relevant analysis

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ThunderCls/xAnalyzer#31]
If I analyze an image and it gets updated afterwards, I see leftovers which are impossible to remove. That's even though I use the "Clear Previous Data" (auto) setting.

![image](https://user-images.githubusercontent.com/5781692/39071579-437908bc-44f0-11e8-99e4-f6270a17a388.png)
![image](https://user-images.githubusercontent.com/5781692/39071639-7a7bae0a-44f0-11e8-8455-1ac39f4464fb.png)

**Comment by ThunderCls** [comment]
Those prev analysis leftovers should be cleared by:
1- Delete the prev x64dbg database file .dd32/.dd64
2- Select Clear Previous Data/User Comments + User Labels, then use "Remove analysis from executable"

If you still can't get rid of them, please post the exe along with the database to give it a closer look

**Comment by justanotheranonymoususer** [comment]
> 1- Delete the prev x64dbg database file .dd32/.dd64

Yes, that works. But it requires restarting the debuggee, and removes other information. Not convenient.

> 2- Select Clear Previous Data/User Comments + User Labels, then use "Remove analysis from executable"

I was surprised to find out that it works. After experimenting, I found out what's going on:
* If I load the exe normally, removing analysis works as expected, or if I just analyze then the old analysis is properly removed.
* If, on the other hand, I **attach** the running exe, removing old analysis doesn't work at all.

It can be tested by having two executables with the same name.
* Load the first one and analyze it.
* Unload it.
* Run the second one, and attach to it.
* Try to remove the analysis.

Let me know if you're able to reproduce this. Thanks.

**Comment by ThunderCls** [comment]
Oh I got you now ;). Just be sure to set your EIP on the correct .text section after you attach and then click on "Remove analysis from executable".

**Comment by justanotheranonymoususer** [comment]
You're right, that works. But that's super unintuitive. If I choose to analyze executable, the previous data removal is done to the module on EIP (?) (what if the debuggee is running?), but the analysis is done to the module which is displayed in the CPU window.

I think that it should be changed so the previous data will be acted on the code in the CPU window, too.

**Comment by ThunderCls** [comment]
The use of cip as the "marker" for the analysis range within a module was used since the first version of xAnalyzer and I never thought too much about it, but I guess I agree with you. It could be changed to get the current disasm selected line as analysis boundaries reference instead of cip.
