### ISSUE TITLE
Strings not showing like in Olly

### ISSUE THREAD

**Issue by Faq** [ThunderCls/xAnalyzer#36]
Hello, tried first time your plugin (https://github.com/ThunderCls/xAnalyzer/releases/tag/2.5.2) with x64 (version released 02.2018).
And didnt got anything like olly shows, image linked:
https://snag.gy/kLEDOg.jpg

Anything I'm doing wrong? Was expecting to see the same like olly shows string: Text="You did it ! U r the man.."

 XAnalyzer using these options for 32 app:
+ Automatic analysis=on
+Extended analysis=on
+Analise undefined functions=on
+Function smart tracking=on

**Comment by ThunderCls** [comment]
It appears that x64dbg is using a different way to present information on the disasm windows in newer versions so that's why xAnalyzer is not properly working anymore. I'm working on it and soon I'll push an update.
Thanks

**Comment by ThunderCls** [comment]
A new version was pushed, update to fix the issue
