### ISSUE TITLE
Function not detected

### ISSUE THREAD

**Issue by Flamefire** [ThunderCls/xAnalyzer#39]
I was just trying this on some gdi32 code and it doesn't detect e.g. BitBlt although it should:

![unbenannt](https://user-images.githubusercontent.com/309017/47995261-ff059c80-e0f4-11e8-91da-3c2cf044e136.png)

The other functions are detected though. When manually analysing the section with the function the log shows 0 for all "defined/undefined functions detected"

**Comment by ThunderCls** [comment]
Thanks for reporting, I'll look into it
