### ISSUE TITLE
Incorrectly parsing argument order

### ISSUE THREAD

**Issue by MoonDoggie42** [ThunderCls/xAnalyzer#42]
Thunder,
The argument order of the xAnalyzer output is incorrect where this assembly is concerned.

![SNAG-0002](https://user-images.githubusercontent.com/13701799/64480876-81cc0d80-d185-11e9-8f0e-22e73af01777.jpg)

If you need more information or the binary, let me know.

Best,
Colin

**Comment by ThunderCls** [comment]
Thanks for reporting, I'll try to fix it asap since it's an easy one

**Comment by MoonDoggie42** [comment]
No problem at all, I do hope it ends up being trivial.  xAnalyzer works wonders so this minor bug isn't affecting anything at all other than a small head scratch why a pointer was in the length. :)
