### ISSUE TITLE
A crash on a too long instruction

### ISSUE THREAD

**Issue by m417z** [ThunderCls/xAnalyzer#43]
Hi,

The analyzer crashes [here](https://github.com/ThunderCls/xAnalyzer/blob/762188132ef53dbca4902037cba77c97a7c6616b/xAnalyzer/xanalyzer.cpp#L480) for me with a specific binary. The issue is that in my case the `szDisasmText` content is 273 characters long, while `GuiInstruction` can't hold that much.

Perhaps `GuiInstruction`'s size needs to be changed from [`MAX_MNEMONIC_SIZE * 4`](https://github.com/ThunderCls/xAnalyzer/blob/762188132ef53dbca4902037cba77c97a7c6616b/xAnalyzer/xanalyzer.h#L38) to [`GUI_MAX_DISASSEMBLY_SIZE`](https://github.com/ThunderCls/xAnalyzer/blob/ab7a422dff21aea3847177355cbde3f1862b64ff/xAnalyzer/pluginsdk/bridgemain.h#L895). Should fix the issue, but I didn't dive into the details.

**Comment by ThunderCls** [comment]
I'll look into it
Thanks for reporting
