### ISSUE TITLE
When Analysis a test file, crashed the debugger and debuggee.

### ISSUE THREAD

**Issue by chuangshizhiqiang** [ThunderCls/xAnalyzer#47]
![image](https://user-images.githubusercontent.com/16714437/87743185-f0a0db00-c81a-11ea-853a-a93dd9dd777a.png)

Crash everytime.

**Comment by ThunderCls** [comment]
Make sure you're using "release" versions of the plugin and x64dbg. I can confirm that it's working fine in the latest version of the debugger (July 11 2020) no probs whatsoever

**Comment by chuangshizhiqiang** [comment]
> Make sure you're using "release" versions of the plugin and x64dbg. I can confirm that it's working fine in the latest version of the debugger (July 11 2020) no probs whatsoever

Yes,and try this.
When I use prebuild version plugin, there is only  crash and exit.So, I build debug version ,and show error message "Buffer si too small"
[1.zip](https://github.com/ThunderCls/xAnalyzer/files/4936957/1.zip)

**Comment by ThunderCls** [comment]
I haven't look too close but It seems related to #43 and buffer size issues.
Thanks for reporting! I'll try to push a fix for both of them asap
