### ISSUE TITLE
x64dbg Oct 2 2020 - plugin load error

### ISSUE THREAD

**Issue by evandrix** [ThunderCls/xAnalyzer#49]
![screenshot](https://user-images.githubusercontent.com/169669/96263766-f6fb4a80-0ff5-11eb-9367-447ba8db4746.png)

> The procedure entry point TitanGetProcessInformation could not be located in the dynamic link library C:\Users\user\Desktop\bin\x96dbg\release\x64\plugins\xAnalyzer.dp64.

**Comment by mrfearless** [comment]
duplicate of #48
