### ISSUE TITLE
Weird letters 

### ISSUE THREAD

**Issue by fautioT** [ThunderCls/xAnalyzer#51]
![Capture d’écran (285)](https://user-images.githubusercontent.com/65911636/113011032-a4fc4a80-9179-11eb-922c-d89d312fb86a.png)
Hello, I have these weird letters, what causes this?

**Comment by ThunderCls** [comment]
You can't just pretend to post a pic of some weird issue you're having with the debugger, without even giving any details or further information about it and expect that just like that, I can magically say what's wrong with it. I don't even see what the plugin has to do with it tbh, so unless you provide prove that this is somehow related to the plugin or you give more information or steps to reproduce I don't see how I can help you

**Comment by FikraHack** [comment]
Bro can you help me pleaze if you want contact me https://www.facebook.com/frsibm

**Comment by ThunderCls** [comment]
@FikraHack if you're having an issue with the plugin open a new github issue, otherwise don't waste your time posting your socials waiting for me to contact you
