### ISSUE TITLE
x32dbg crash when analyzing module

### ISSUE THREAD

**Issue by UrbanCMC** [ThunderCls/xAnalyzer#53]
Even after turning all extra options off, some applications cause x32dbg to crash when either doing `xAnalyzer -> Analyze Module`, or when enabling `Automatic Analysis`.
The status bar reaches `[xAnalyzer]: Doing extended analysis...98%`, after which x32dbg crashes without an error message.

The only information about the crash I can find is in the Event Viewer:
![image](https://user-images.githubusercontent.com/9725089/119322273-c52e1e80-bc7d-11eb-9a25-2ae4dd3c0752.png)

Example application causing the crash: https://crackinglessons.com/crackme-9/

**Comment by ThunderCls** [comment]
Thanks for reporting, it looks like a bof when setting a comment.

**Comment by HackBd1** [comment]
貌似插件不起作用
