### ISSUE TITLE
Cant be installed on last version!!

### ISSUE THREAD

**Issue by Formingus** [ThunderCls/xAnalyzer#55]
D:\Cracking\x64\release\x64\plugins\apis_def\apis_def.zip - Line: 1 
            Check the malformed file/line and try again...exiting plugin initialization! 

LOG

**Comment by ThunderCls** [comment]
You need to unzip de apis_def file. Check the installation instructions in the readme

**Comment by Formingus** [comment]
> You need to unzip de apis_def file. Check the installation instructions in the readme

Hi Friend, thanks it worked.. 
I think you should update the installation instruction, bcz there is no unzip mentioned. Thanks
`Installation
Download the latest version of x64dbg

Copy xAnalyzer.dp32/xAnalyzer.dp64 files and apis_def folder to x32/x64 respective plugins directories of x64dbg

Look under the "Plugins" menu in the main x64dbg window or in the secondary menu in the Disasm window as well for an "xAnalyzer" entry

If, after following the above steps can't see the menu entry under the "Plugins" menu, head to the "Log" tab and check for any message from the plugin that could give you an error solution hint`

**Comment by ThunderCls** [comment]
apis_def.zip is not a folder, but it contains an apis_defs folder inside it. Either way, I guess we could specifically state that fact in the instructions

**Comment by Formingus** [comment]
> apis_def.zip is not a folder, but it contains an apis_defs folder inside it. Either way, I guess we could specifically state that fact in the instructions

Understand but sometimes zip files can be used in a temporary way, sw will extract, use, delete, anyway, it's your project and you will decide. All the best

**Comment by Formingus** [comment]
> apis_def.zip is not a folder, but it contains an apis_defs folder inside it. Either way, I guess we could specifically state that fact in the instructions

Getting this problem , any idea ?
![2021-11-17_203659](https://user-images.githubusercontent.com/37929267/142278646-12d89e94-5fab-48cb-8c84-aa9339e3da25.jpg)

**Comment by ThunderCls** [comment]
Make sure that you're using TitanEngine on x64dbg. Check #48

**Comment by Formingus** [comment]
> Make sure that you're using TitanEngine on x64dbg. Check #48

Thanks , that worked
