### ISSUE TITLE
Automatic comments are inserted with preceding "\1"

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ThunderCls/xAnalyzer#6]
![screenshot](http://i.imgur.com/lLDKqmk.png)

**Comment by ThunderCls** [comment]
Thanks

**Comment by ThunderCls** [comment]
could you provide the executable, please?

**Comment by justanotheranonymoususer** [comment]
I found this in explorer.exe. Cannot find it now anymore. It's a temporary comment of x64dbg, which shows the content of some register,

**Comment by ThunderCls** [comment]
Apparently I'm not able to replicate that...

![image](https://cloud.githubusercontent.com/assets/13303069/21284877/a78de574-c3f6-11e6-90b9-94e3c2e07285.png)

**Comment by justanotheranonymoususer** [comment]
Switch your font to "Terminal". The default font doesn't display the `'\1'` character. But note that if you copy the disassembly, you get that character.

**Comment by ThunderCls** [comment]
Ok @justanotheranonymoususer, thanks, it's fixed now, coming in the next update
